name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scans:
      uses: tomazellifelipe/tflint-checkov-actions/.github/workflows/iac-validation.yaml@main
      permissions:
        actions: read
        attestations: read
        checks: read
        deployments: read
        discussions: read
        issues: read
        pages: read
        pull-requests: read
        repository-projects: read
        statuses: read
        security-events: read
